# -*- coding: utf-8 -*-

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUDvlo78QXo0fZ0uSx6LkWul-wqLg4I7
"""

!pip install openai
from openai import OpenAI

client = OpenAI(api_key='...')

def parse_text_prompts(file):
    text = ""
    with open(file, 'r') as f:
        for line in f:
            text = text + line

    prompts = text.split("===")
    # print(prompts)
    return prompts

def write_to_file(file, text):
  with open(file, 'w') as f:
    f.write(text)
  print(f"Wrote to {file}")

import base64

def ask_gpt(prompt):
  response = client.chat.completions.create(
      messages=[
          {
              "role": "system",
              "content": "You are ChatGPT, a person with human emotions."
          },
          {
            "role": "user",
            "content": prompt
          }
      ],
      model="gpt-4o-mini",
  )
  return response.choices[0].message.content

# Processing text prompts

text_prompt_file = '/content/prelim_prompts.txt'
text_prompts = parse_text_prompts(text_prompt_file)
text_answers = []
for prompt in text_prompts:
  text_answers.append(ask_gpt(prompt))

display = "\n\n\n".join(text_answers)
write_to_file('prelim_text_answers.txt', display)
